using Ecom.Domain.Entities;

namespace Ecom.Application.Features.Commerce.System.Queries.GetManagementSecurity;

public sealed record GetManagementUserSessionsQuery : IRequest<TResult<PaginatedList<ManagementUserSessionDto>>>
{public Guid? UserId{get;init;}public bool? IsRevoked{get;init;}public int Page{get;init;}=1;public int PageSize{get;init;}=50;public int Skip()=> (Page-1)*PageSize;}
public sealed class GetManagementUserSessionsQueryValidator:AbstractValidator<GetManagementUserSessionsQuery>{public GetManagementUserSessionsQueryValidator(){RuleFor(x=>x.Page).GreaterThan(0);RuleFor(x=>x.PageSize).InclusiveBetween(1,100);}}
public sealed class GetManagementUserSessionsQueryHandler(IUnitOfWork uow,ICurrentUser currentUser):IRequestHandler<GetManagementUserSessionsQuery,TResult<PaginatedList<ManagementUserSessionDto>>>
{public async Task<TResult<PaginatedList<ManagementUserSessionDto>>> Handle(GetManagementUserSessionsQuery r,CancellationToken ct){if(!currentUser.IsAuthenticated)return TResult<PaginatedList<ManagementUserSessionDto>>.Failure(MessageKey.Unauthorized,ErrorCodes.UNAUTHORIZED);if(!currentUser.HasPolicy(Permissions.SecuritySessions.Read))return TResult<PaginatedList<ManagementUserSessionDto>>.Failure(MessageKey.Forbidden,ErrorCodes.FORBIDDEN);var q=from s in uow.Repository<UserSession>().QueryNoTracking() join u in uow.Repository<User>().QueryNoTracking() on s.UserId equals u.Id select new{s,u};if(r.UserId.HasValue)q=q.Where(x=>x.s.UserId==r.UserId);if(r.IsRevoked.HasValue)q=r.IsRevoked.Value?q.Where(x=>x.s.RevokedAt!=null):q.Where(x=>x.s.RevokedAt==null);var total=await q.CountAsync(ct);var rows=await q.OrderByDescending(x=>x.s.LastSeenAt).Skip(r.Skip()).Take(r.PageSize).Select(x=>new ManagementUserSessionDto(x.s.Id,x.s.UserId,x.u.FullName??x.u.Username,x.u.PhoneNumber,x.s.ClientType,x.s.AuthenticationMethod,x.s.AuthenticationStrength,x.s.DeviceId,x.s.CreatedAt,x.s.LastSeenAt,x.s.IdleExpiresAt,x.s.AbsoluteExpiresAt,x.s.RevokedAt,x.s.RevocationReason)).ToListAsync(ct);return TResult<PaginatedList<ManagementUserSessionDto>>.Success(PaginatedList<ManagementUserSessionDto>.Create(rows,total,r.Page,r.PageSize));}}
