using Ecom.Application.Features.AuthV2;
using Ecom.Domain.Entities;
using Ecom.Domain.Enums;
using System.Security.Cryptography;
using Microsoft.Extensions.Options;
using Ecom.Application.Common.Configuration;

namespace Ecom.Application.Features.AuthV2.PasswordManagement;
public sealed record ForgotPasswordCommand(string Email):IRequest<TResult<Register.RegisterPasswordResult>>;
[EnableUnitOfWork] public sealed record ResetPasswordCommand(string Token,string NewPassword):IRequest<TResult>;
[EnableUnitOfWork] public sealed record ChangePasswordCommand(string CurrentPassword,string NewPassword):IRequest<TResult>;
[EnableUnitOfWork] public sealed record SetupPasswordCommand(string Username,string Password):IRequest<TResult>;
public sealed class ForgotPasswordValidator:AbstractValidator<ForgotPasswordCommand>{public ForgotPasswordValidator(){RuleFor(x=>x.Email).NotEmpty().EmailAddress();}}
public sealed class ResetPasswordValidator:AbstractValidator<ResetPasswordCommand>{public ResetPasswordValidator(IOptions<PasswordSettings> settings){RuleFor(x=>x.Token).NotEmpty();RuleFor(x=>x.NewPassword).Must(x=>PasswordRules.ValidPassword(x,settings.Value.MinLength));}}
public sealed class ChangePasswordValidator:AbstractValidator<ChangePasswordCommand>{public ChangePasswordValidator(IOptions<PasswordSettings> settings){RuleFor(x=>x.CurrentPassword).NotEmpty();RuleFor(x=>x.NewPassword).Must(x=>PasswordRules.ValidPassword(x,settings.Value.MinLength));}}
public sealed class SetupPasswordValidator:AbstractValidator<SetupPasswordCommand>{public SetupPasswordValidator(IOptions<PasswordSettings> settings){RuleFor(x=>x.Username).Must(PasswordRules.ValidUsername);RuleFor(x=>x.Password).Must(x=>PasswordRules.ValidPassword(x,settings.Value.MinLength));}}

public sealed class ForgotPasswordHandler(IUnitOfWork uow,IAuthTokenProtector protector,IOptions<EmailVerificationOptions> options):IRequestHandler<ForgotPasswordCommand,TResult<Register.RegisterPasswordResult>>
{public async Task<TResult<Register.RegisterPasswordResult>> Handle(ForgotPasswordCommand r,CancellationToken ct){if(!options.Value.Enabled)return TResult<Register.RegisterPasswordResult>.Failure(MessageKey.AuthDependencyUnavailable,ErrorCodes.SERVICE_UNAVAILABLE);var email=r.Email.Trim().ToUpperInvariant();var user=await uow.Repository<User>().FindOneAsync([x=>x.NormalizedEmail==email]);if(user is not null){var raw=B64(RandomNumberGenerator.GetBytes(32));var now=DateTime.UtcNow;await uow.Repository<VerificationChallenge>().InsertAsync(new(user.Id,VerificationChallengePurpose.PasswordReset,protector.Protect(email),protector.Protect(raw),5,now.AddMinutes(30),"recovery"),ct);await uow.SaveChangesAsync(ct);}return TResult<Register.RegisterPasswordResult>.Success(new("Accepted"));}private static string B64(byte[]b)=>Convert.ToBase64String(b).TrimEnd('=').Replace('+','-').Replace('/','_');}

public sealed class ResetPasswordHandler(IUnitOfWork uow,IPasswordHasher hasher,IAuthTokenProtector protector):IRequestHandler<ResetPasswordCommand,TResult>
{public async Task<TResult> Handle(ResetPasswordCommand r,CancellationToken ct){var now=DateTime.UtcNow;var hash=protector.Protect(r.Token);var c=await uow.Repository<VerificationChallenge>().FindOneAsync([x=>x.SecretHash==hash&&x.Purpose==VerificationChallengePurpose.PasswordReset],"CreatedAt desc");if(c is null||!c.IsUsable(now)||!c.UserId.HasValue)return TResult.Failure(MessageKey.AuthenticationFailed,ErrorCodes.UNAUTHORIZED);var user=await uow.Repository<User>().FindByIdAsync(c.UserId.Value);var credential=await uow.Repository<PasswordCredential>().FindOneAsync([x=>x.UserId==c.UserId]);if(user is null||credential is null)return TResult.Failure(MessageKey.AuthenticationFailed,ErrorCodes.UNAUTHORIZED);credential.SetHash(hasher.HashPassword(r.NewPassword),now);c.Consume(now);user.RotateSecurityStamp();await RevokeAll(uow,user.Id,now,ct);await uow.Repository<PasswordCredential>().UpdateAsync(credential,ct);await uow.Repository<VerificationChallenge>().UpdateAsync(c,ct);await uow.Repository<User>().UpdateAsync(user,ct);await uow.Repository<SecurityEvent>().InsertAsync(new(user.Id,null,"PasswordResetSucceeded",SecurityRiskLevel.Medium,true,"not-captured","not-captured",null,now),ct);return TResult.Success();}internal static async Task RevokeAll(IUnitOfWork uow,Guid userId,DateTime now,CancellationToken ct){var sessions=await uow.Repository<UserSession>().FindAsync([x=>x.UserId==userId&&x.RevokedAt==null]);foreach(var s in sessions){s.Revoke(now,"PasswordChanged");await uow.Repository<UserSession>().UpdateAsync(s,ct);var ts=await uow.Repository<SessionRefreshToken>().FindAsync([x=>x.SessionId==s.Id&&x.RevokedAt==null]);foreach(var t in ts){t.Revoke(now);await uow.Repository<SessionRefreshToken>().UpdateAsync(t,ct);}}}}

public sealed class ChangePasswordHandler(IUnitOfWork uow,ICurrentUser current,IPasswordHasher hasher):IRequestHandler<ChangePasswordCommand,TResult>
{public async Task<TResult> Handle(ChangePasswordCommand r,CancellationToken ct){if(!current.IsAuthenticated)return TResult.Failure(MessageKey.Unauthorized,ErrorCodes.UNAUTHORIZED);var user=await uow.Repository<User>().FindByIdAsync(current.UserId);var credential=await uow.Repository<PasswordCredential>().FindOneAsync([x=>x.UserId==current.UserId]);if(user is null||credential is null||!hasher.VerifyPassword(r.CurrentPassword,credential.PasswordHash))return TResult.Failure(MessageKey.AuthenticationFailed,ErrorCodes.UNAUTHORIZED);var now=DateTime.UtcNow;credential.SetHash(hasher.HashPassword(r.NewPassword),now);user.RotateSecurityStamp();await ResetPasswordHandler.RevokeAll(uow,user.Id,now,ct);await uow.Repository<User>().UpdateAsync(user,ct);await uow.Repository<PasswordCredential>().UpdateAsync(credential,ct);return TResult.Success();}}

public sealed class SetupPasswordHandler(IUnitOfWork uow,ICurrentUser current,IPasswordHasher hasher):IRequestHandler<SetupPasswordCommand,TResult>
{public async Task<TResult> Handle(SetupPasswordCommand r,CancellationToken ct){if(!current.IsAuthenticated)return TResult.Failure(MessageKey.Unauthorized,ErrorCodes.UNAUTHORIZED);var user=await uow.Repository<User>().FindByIdAsync(current.UserId);if(user is null||user.EmailVerifiedAt is null)return TResult.Failure(MessageKey.AuthenticationFailed,ErrorCodes.FORBIDDEN);if(await uow.Repository<PasswordCredential>().AnyAsync([x=>x.UserId==user.Id])||await uow.Repository<User>().AnyAsync([x=>x.NormalizedUsername==r.Username.Trim().ToUpperInvariant()&&x.Id!=user.Id]))return TResult.Failure(MessageKey.AuthenticationFailed,ErrorCodes.ALREADY_EXISTS);user.SetUsername(r.Username);await uow.Repository<User>().UpdateAsync(user,ct);await uow.Repository<PasswordCredential>().InsertAsync(new(user.Id,hasher.HashPassword(r.Password),DateTime.UtcNow),ct);return TResult.Success();}}
